#!/bin/bash

# restore a website from from backup
#
#		Author	: Viki (a) Vignesh Natarajan 
#		Contact	: vikilabs.org
#		Licence : MIT


INPUT=$1

function get_current_dir()
{
    CURRENT_DIR=`pwd -P`
}

function arg_check()
{
    if [ -z "$INPUT" ]; then
        echo "  [ ERROR ] backup file name missing "
        echo
        echo "  [ EXAMPLE ] ./restore_website backup.tar.gz"
        echo
        exit 1
    fi
}

function db_empty_check()
{
    table_count=$(mysql -u$DB_USERNAME -p$DB_PASSWORD -h $DB_HOST -P $DB_PORT $DB_NAME -e "SHOW TABLES;" | wc -l)

    if [ $table_count -gt 0 ];then
        echo "  [ ERROR ] [ ${LINENO} ] DB is not empty ( table_count : $table_count ), truncate database before restore"
        echo
        echo "      -> $DB_NAME"
        echo
        echo
        exit 1
    fi
}

function dir_empty_check()
{
    file_count=`ls ${WEBSITE_ROOT_DIR}/ | wc -l`
    if [ $file_count -gt 0 ];then
        echo "  [ ERROR ] [ ${LINENO} ] website root directory is not empty, clear all files before restoring"
        echo
        echo "      -> $WEBSITE_ROOT_DIR"
        echo
        echo
        exit 1
    fi
}

function validate_input()
{

    echo
    SOURCE_FILE=`basename $INPUT`
    SOURCE_PATH=`dirname $INPUT`

    # GET ABSOLUTE PATH 
    cd $SOURCE_PATH
    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
    SOURCE_PATH=`pwd -P`

    cd $SOURCE_PATH
    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }

    # EXTRACT FILENAME AND PATH FROM INPUT 

    STRIP_EXTN1="${SOURCE_FILE%.*}"
    EXTN1="${SOURCE_FILE##*.}"

    STRIP_EXTN2="${STRIP_EXTN1%.*}"
    EXTN2="${STRIP_EXTN1##*.}"

    RESTORE_DIR=$STRIP_EXTN2


    #echo " EXTENSION 1          : " $EXTN1
    #echo " EXTENSION 2          : " $EXTN2
    #echo " EXTENSION 1 STRIPPED : " $STRIP_EXTN1
    #echo " EXTENSION 2 STRIPPED : " $STRIP_EXTN2
    #echo " RESTORE DIR          : " $RESTORE_DIR


    if [ "$EXTN1" != "gz" ]; then
        echo "  [ ERROR ] invalid backup file name ( file name should end with .tar.gz ) "
        echo
        exit 1
    fi

    if [ "$EXTN2" != "tar" ]; then
        echo "  [ ERROR ] invalid backup file name ( file name should end with .tar.gz ) "
        echo
        exit 1
    fi
}

function get_user_confirmation()
{

    while true; do
        read -p "  Do you wish to restore this website from backup ( YES / NO )?  " user_input
        echo
        case $user_input in
            [YES]* ) echo "  YES : Restore Initiated"; break;;
            * ) echo "  NO ( DEFAULT )  : Aborting Restore Operation";echo;exit;;
        esac
    done
    echo

}

function extract_backup_archive()
{
    echo
    echo "  Extracting backup file : $SOURCE_FILE"
    echo

    # Enter backup directory
    cd $SOURCE_PATH
    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }

    # Remove Old Restore Folder ( if any )
    rm -rf $RESTORE_DIR

    # Extract backup archive
    tar -zxvf $SOURCE_FILE 1> /dev/null
    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
    echo
}

#Old Configuration
function import_config()
{
    source $SOURCE_PATH/$RESTORE_DIR/restore_config.sh
    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }

}

function check_whether_webroot_dir_inside_backup_dir()
{
    # Example:
    #   
    #   if (/home/backup/website) inside ( /home/backup ) : TRUE 
    #   
    if [[ $WEBSITE_ROOT_DIR =~ "$SOURCE_PATH/$RESTORE_DIR" ]]; then
        echo
        echo "  [ possible error ] It looks like new website root directory is inside source directory"
        echo
        echo "       -> [ SOURCE_DIR : $SOURCE_PATH/$RESTORE_DIR ]"
        echo
        echo "       -> [ WEBSITE_ROOT_DIR : $WEBSITE_ROOT_DIR ]"
        echo
        echo "  [ fix ] move tar file ( $SOURCE_PATH/$SOURCE_FILE ) to some other directory and try again"
        echo
        exit 1
    fi  
} 

function empty_config_check_old()
{
    config_error=0

    echo
    [ -z $DOMAIN ] && { echo "  [ CONFIG ERROR ] :  DOMAIN" ; config_error=1; }
    [ -z $DB_NAME ] && { echo "  [ CONFIG ERROR ] :  DB_NAME" ; config_error=1; }
    [ -z $DB_USERNAME ] && { echo "  [ CONFIG ERROR ] :  DB_USERNAME" ; config_error=1; }
    [ -z $DB_PASSWORD ] && { echo "  [ CONFIG ERROR ] :  DB_PASSWORD" ; config_error=1; }
    [ -z $DB_HOST ] && { echo "  [ CONFIG ERROR ] :  DB_HOST" ; config_error=1; }
    [ -z $DB_PORT ] && { echo "  [ CONFIG ERROR ] :  DB_PORT" ; config_error=1; }
    [ -z $WEBSITE_ROOT_DIR ] && { echo "  [ CONFIG ERROR ] :  WEBSITE_ROOT_DIR" ; config_error=1; }
    [ -z $BACKUP_DIR ] && { echo "  [ CONFIG ERROR ] :  BACKUP_DIR" ; config_error=1; }
    [ -z $LOG_FILE ] && { echo "  [ CONFIG ERROR ] :  LOG_FILE" ; config_error=1; }

    if [ $config_error -eq 1 ]; then
        echo
        echo "  [ ERROR ] Fix configuration error and try again ( $SOURCE_PATH/$RESTORE_DIR/restore_config.sh ) "
        echo
        exit 1
   fi
}

function remove_trailing_slash_old()
{
   BACKUP_DIR=`echo ${BACKUP_DIR%/}`
   BACKUP_DIR=`echo ${BACKUP_DIR%/}`
   
   WEBSITE_ROOT_DIR=`echo ${WEBSITE_ROOT_DIR%/}`
   WEBSITE_ROOT_DIR=`echo ${WEBSITE_ROOT_DIR%/}`
   
   DOMAIN=`echo ${DOMAIN%/}`
   DOMAIN=`echo ${DOMAIN%/}`
}

function print_config()
{
    echo
    echo "  PREVIOUS SERVER CONFIGURATION"
    echo
    echo "  DOMAIN            : $DOMAIN"
    echo "  Website Root      : $WEBSITE_ROOT_DIR"
    echo "  DB NAME           : $DB_NAME"
    echo "  DB USER           : $DB_USERNAME"
    echo "  DB PASSWORD       : $DB_PASSWORD"
    echo "  DB HOST           : $DB_HOST"
    echo "  DB PORT           : $DB_PORT"
    echo 
    echo
    echo "  Note: Make sure your existing config is same as above. If not use the following command,"
    echo
    echo "  ./migrate_website $INPUT"
    echo
    echo

}

function get_abs_path_website_root()
{
    cd $WEBSITE_ROOT_DIR
    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
    WEBSITE_ROOT_DIR=`pwd -P`
}

function importe_database()
{
    cd $SOURCE_PATH
    mysql -u$DB_USERNAME  -p$DB_PASSWORD $DB_NAME < ${RESTORE_DIR}/db/database.sql
    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Database Import Failed"; exit 1; }
}

function importe_code()
{
    cd $SOURCE_PATH
    mv ${RESTORE_DIR}/code/* ${WEBSITE_ROOT_DIR}/
    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Website copy failed"; exit 1; }
}

function restore_success()
{
    echo
    echo "  [ SUCCESS ] website restore successfully ( $DOMAIN )"
    echo
}


function main()
{
    get_current_dir
    arg_check
    validate_input
    get_user_confirmation
    extract_backup_archive
    import_config
    check_whether_webroot_dir_inside_backup_dir
    empty_config_check_old
    remove_trailing_slash_old
    print_config
    get_abs_path_website_root
    db_empty_check
    dir_empty_check
    importe_database
    importe_code
    restore_success
}

# Call Main Function
main
